### ISSUE TITLE
render comment headers correctly

### ISSUE THREAD

**Issue by TLINDEN** [Lindydancer/el2markdown#10]
Hi,

First of all: thanks for this library, it's exactly what I was looking for!

My commentary sections usually contain comment headers using multiple ; to indicate the level, highlighted properly by outline-minor-mode. I'd expect el2markdown to render those headers appropriately to markdown, but it doesn't ([example](https://github.com/TLINDEN/config-general-mode)).

Also (with the same .el file), it stops too early before the ";;;; Usage" header.

best regards,
Tom

**Comment by Lindydancer** [comment]
Hi!

> First of all: thanks for this library, it's exactly what I was looking for!
>
You're welcome!

> My commentary sections usually contain comment headers using multiple ; to
> indicate the level, highlighted properly by outline-minor-mode. I'd expect
> el2markdown to render those headers appropriately to markdown, but it
> doesn't (example <https://github.com/TLINDEN/config-general-mode>).
>
You will have to format the comments in a special way for el2markdown to
recognise them. Basically, there are two rules:

1) Headers should end with a colon.

2) All lines in a section should start with ";;", even the empty lines.

So, if you replace:

;;;; Installation

;; To use, save config-general-mode.el to a directory in your load-path.

;; Add something like this to your config:

;;     (require 'config-general-mode)
;;     (add-to-list 'auto-mode-alist '("\\.conf$" . config-general-mode))

With:

;;;; Installation:
;;
;; To use, save config-general-mode.el to a directory in your load-path.
;;
;; Add something like this to your config:
;;
;;     (require 'config-general-mode)
;;     (add-to-list 'auto-mode-alist '("\\.conf$" . config-general-mode))

it should work straight out of the box.

el2markdown, however, does not base the heading level on the number of
semicolons used. Instead, a header at the beginning of a comment block is
treated as a "##" header and a header inside a comment block a "###" header.

Also (with the same .el file), it stops too early before the ";;;; Usage"
> header.
>
This was actually not due to the ";;;; Usage" header. Your file contains
some stray space characters, for example on line 58. My code didn't expect
them, and stopped processing the header. I just published a fix for this,
so it should start working if you update el2markdown.

Thanks for reporting both issues!

    -- Anders

**Comment by TLINDEN** [comment]
Hi,

> You will have to format the comments in a special way for el2markdown to recognise them. 

Ok, I changed this and it works now as expected. Great!

> Your file contains some stray space characters

Oh, shit. I was not aware of this and enabled `show-trailing-spaces` for elisp mode, thanks for finding this!




Thanks,
Tom
