### ISSUE TITLE
Issue marking lines as sub-headings and retaining blank lines in code blocks

### ISSUE THREAD

**Issue by kaushalmodi** [Lindydancer/el2markdown#7]
Hi Anders,

I used this package for the first time yesterday. I need help getting the correct way to write the elisp comments to get the desired markdown output

``` el
;; This package has been tested to work with the latest version of org built
;; from the master branch ( http://orgmode.org/cgit.cgi/org-mode.git ) as of
;; Aug 10 2016.
;;
;; EXAMPLE ORG FILE:
;;
;;     #+TITLE: My notes
;;
;;     * Heading 1
;;     ** Sub heading
;;     *** More nesting
;;     - List item 1
;;     - List item 2
;;     - List item 3
;;     * Heading 2
;;     ** Sub heading
;;     - List item 1
;;     - List item 2
;;     - List item 3
;;     *** More nesting
;;
;; MINUTES EXPORT (!this line is NOT exported as sub-heading!):
;;
;;                                    __________
;;
;;                                     MY NOTES
;;                                    __________
;;
;;     * Heading 1
;;       + Sub heading
;;         - More nesting
;;           - List item 1
;;           - List item 2
;;           - List item 3
;;
;;     * Heading 2 (!I need to retain the blank line above IN the code block!)
;;       + Sub heading
;;         - List item 1
;;         - List item 2
;;         - List item 3
;;         - More nesting

;;; Code:
```

Here is the generated .md that shows the 2 issues:

- The `MINUTES EXPORT` does not become a sub-heading
- I like to delete all white-spaces in the code. So I lose the blank line above the `* Heading 2`.

```md
This package has been tested to work with the latest version of org built
from the master branch ( http://orgmode.org/cgit.cgi/org-mode.git ) as of
Aug 10 2016.

## EXAMPLE ORG FILE

    #+TITLE: My notes

    * Heading 1
    ** Sub heading
    *** More nesting
    - List item 1
    - List item 2
    - List item 3
    * Heading 2
    ** Sub heading
    - List item 1
    - List item 2
    - List item 3
    *** More nesting

MINUTES EXPORT (!this line is NOT exported as sub-heading!):

                                   __________

                                    MY NOTES
                                   __________

    * Heading 1
      + Sub heading
        - More nesting
          - List item 1
          - List item 2
          - List item 3
    * Heading 2 (!I need to retain the blank line above IN the code block!)
      + Sub heading
        - List item 1
        - List item 2
        - List item 3
        - More nesting
```

**Comment by kaushalmodi** [comment]
I was able to resolve one of the two problems, the problem with sub-heading parsing.

Apparently, I need to have

```el
;; foo

;; sub-heading1:
;; foo

;; sub-heading2:
;; foo
```

instead of 

```el
;; foo
;;
;; sub-heading1:
;; foo
;;
;; sub-heading2:
;; foo
```

So, changing to the below fixed that part:

```el
;; This package has been tested to work with the latest version of org built
;; from the master branch ( http://orgmode.org/cgit.cgi/org-mode.git ) as of
;; Aug 10 2016.

;; EXAMPLE ORG FILE:
;;
;;     #+TITLE: My notes
;;
;;     * Heading 1
;;     ** Sub heading
;;     *** More nesting
;;     - List item 1
;;     - List item 2
;;     - List item 3
;;     * Heading 2
;;     ** Sub heading
;;     - List item 1
;;     - List item 2
;;     - List item 3
;;     *** More nesting

;; MINUTES EXPORT:
;;
```

Now I am looking into how to convey to `el2markdown` that I intend to keep a blank line in the code block.

**Comment by kaushalmodi** [comment]
This PR ( https://github.com/Lindydancer/el2markdown/pull/8 ) fixes the blank line issue for me.

**Comment by Lindydancer** [comment]
Hi!

I took at look at the PR and the problems you were experiencing.

The first case, when the heading was not translated into a MarkDown heading
is due to an exception that a line ending with a colon that precedes a code
block isn't treated as a heading. This ensure that text lines introducing a
code block aren't converted to headings, as is:

;; This is a heading:
;;
;; text text text.
;;
;; This is a subheading:
;;
;; text text text.
;;
;; This line talks about the code example below as is not a heading:
;;
;;         1 + 2 + 3 = 6

In your case, if can either start a new comment section (which is the
solution you found yourself) or do something like:

;; EXAMPLE ORG FILE:
;;
;; Text text text
;;
;; MINUTES EXPORT:
;;
;; The following is my notes.
;;
;;     * Heading 1
;;       + Sub heading
;;         - More nesting

When it comes to the PR concerning the extra blank line, what about the
following change instead? Logically, it does the same as your but in a more
straight forward way:

===================================================================
--- el2markdown.el (revision 1678)
+++ el2markdown.el (working copy)
@@ -320,10 +320,12 @@


 (defun el2markdown-is-at-bullet-list ()
+  "Non-nil when next non-empty comment line is a bullet list."
   (save-excursion
     (while (looking-at "^;;$")
       (forward-line))
-    (looking-at ";;+ *[-*]")))
+    ;; When more then 4 spaces, the line is a code block.
+    (looking-at ";;+ \\{0,4\\}[-*]")))

 (defun el2markdown-emit-rest-of-comment ()
   (let ((first t))


Please try it out -- if it works for you I'll push a new version as soon as
possible.

Sincerely,
    Anders

**Comment by kaushalmodi** [comment]
Your suggested patch works. Please go ahead and commit it.

Thanks.
